### ISSUE TITLE
Where do you get/find design inspiration?

### ISSUE THREAD

**Issue by darcyclarke** [darrinhenein/ama#4]

**Comment by darrinhenein** [comment]
I tend to gravitate to more traditional media for inspiration–I’ve tried to use tools like Pinterest and Dribbble to explore and be inspired, but as so much of my work occurs on a  computer, I often find it more useful to step back from the screen. 

I love to read, and find a lot of inspiration from fiction. Reading forces you to envision what is being described to you, and this act alone often pops ideas and visuals into my mind. Film and music are similar, they both tell stories but leave gaps for you to fill in, and (for me at least) this often sparks interesting new trains of thought.

I also think we allow ourselves to be too busy, and ignore the incredible power of the subconscious. I often fall into the trap that I should always be doing something productive: reading a book, listening to a podcast, or writing some code. There is a reason so many revolutionary ideas occurred while taking a shower or shaving (Einstein is noted for this); in these times of seeming monotony our brain is left to wander and explore, often prompting unlikely connections or revelations to surface. I make a point of finding these times of quiet, on the train or on my patio after dinner, to just let my mind wander. Aside from being a great stress reliever, it can also be a very healthy creative habit!

**Comment by darcyclarke** [comment]
:+1: I like this a lot.

**Comment by akashnimare** [comment]
@darrinhenein What podcasts do you listen?
