### ISSUE TITLE
Who's your favorite superhero?

### ISSUE THREAD

**Issue by sindresorhus** [darrinhenein/ama#8]

**Comment by darrinhenein** [comment]
I think it’s always been Batman, and I don’t know why. I love the Nolan trilogy, but even before those were some great animated series. He was just more real to me, I could understand his pain and loss, and his reclusiveness. Turning his fear into his strength. He didn’t have supernatural powers to draw on, so he had to be smart. 

I guess in some entirely nerdy way I just have more respect for someone like that than for someone who can fly or shoot lasers out his face or something.
